#!/usr/bin/env python

import sys

from rqt_gui.main import Main


main = Main()
sys.exit(main.main(
    sys.argv,
    # Note to follow the this structure to launch correctly
    # '(after src directory name)/(python file name)/(class name)'
    standalone='ros_rqt_plugin.ros_rqt_plugin.Buttons'
))